Iter23
vkhrushchev/urlshortener pull request #27
Opened 2024-12-25 13:18 UTC by vkhrushchev

2024-12-28 15:03 UTC, bulbetski requested changes
требуются микроизменения

2024-12-28 15:03 UTC, bulbetski commented on cmd/shortener/flags.go
> +type Config struct {
в cmd'шке должен быть только main. Вынести это в пакет config и файл тоже стоит назвать config.go, потому что он про конфиг, а не про флаги

2024-12-28 15:03 UTC, bulbetski commented on internal/app/app.go
> +	gracefulShutdownChan := make(chan struct{})
Не вижу, где используется

2024-12-31 12:08 UTC, vkhrushchev commented on cmd/shortener/flags.go
> +type Config struct {
Поправил.

2024-12-31 12:09 UTC, vkhrushchev commented on internal/app/app.go
> +	gracefulShutdownChan := make(chan struct{})
Упс. Добавил ожидание закрытия канала.

2025-01-15 08:56 UTC, bulbetski approved these changes
config надо сделать пакетом на одном уровне с internal

то есть у тебя будет 

cmd
config
internal

2025-01-16 12:34 UTC, merged