Iter9
vkhrushchev/urlshortener pull request #9
Opened 2024-07-30 06:46 UTC by vkhrushchev

2024-07-31 08:34 UTC, tmvrus requested changes
работа хорошая, но есть ряд вопросов по работе с файлами

2024-07-31 08:34 UTC, tmvrus commented on cmd/shortener/main.go
> +		os.Exit(1)
в проекте уже есть логер, разумно его использовать, две эти строки можно заменить на log.Fatal(err)

2024-07-31 08:34 UTC, tmvrus commented on cmd/shortener/main.go
>  		os.Exit(1)
тут тоже можно использовать log.Fatal

2024-07-31 08:34 UTC, tmvrus commented on internal/app/app.go
> +		panic("cannot initilize zap")
Тут следует помнить, что паника брошенная в init() не может быть перехвачена и обработана внешним кодом, если это конечно нужно.

2024-07-31 08:34 UTC, tmvrus commented on internal/app/storage/storage.go
> +	file.Write(storageJSONBytes)
тут сразу несколько вопросов:
- если файл не получится открыть, всего лишь будет напечатана ошибка (почему бы не использовать тут логер?) но код работать не прекратит, что придет к панике в file.Close()
- при вызове json.Marshal игнорируется ошибка, тут это не приведет к каким либо последствиям, но следует приучить себя обрабатывать любые возможные ошибки, это признак профессионализма
- игнорируется ошибка записи file.Write, если записать данные не получится, клиент об этом никогда не узнает
- игнорируется ошибка file.Close, если метод вернет ошибку, то файл не будет правильно записан и мы никогда об этом не узнаем

2024-08-02 02:17 UTC, vkhrushchev commented on cmd/shortener/main.go
>  		os.Exit(1)
исправлено

2024-08-02 02:17 UTC, vkhrushchev commented on internal/app/app.go
> +		panic("cannot initilize zap")
исправлено

2024-08-02 02:33 UTC, vkhrushchev commented on internal/app/storage/storage.go
> +	file.Write(storageJSONBytes)
исправлено

2024-08-02 02:57 UTC, vkhrushchev commented on cmd/shortener/main.go
> +		os.Exit(1)
исправлено

2024-08-05 08:41 UTC, tmvrus approved these changes

2024-08-08 02:03 UTC, merged